{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 141418,
          "sha512": "84386fddf167e8f981705629fa3f55ca56e8b2b6f7f06a1410413c9a41429d296d2d050d7531c2c21d22c0f3205f45fbd54bed35311dd64bc482613df91380b6",
          "sha256": "39a7aa3e7cd64f5dc72883746cf9b11862443aa5a22a5ba41f4743bc4f720d51",
          "sha1": "754994f9c2e71c58c1b861a8bac18e93ddf7f641",
          "md5": "98ca89c6f9845904ca6aac44e4faee27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 141418,
          "sha512": "84386fddf167e8f981705629fa3f55ca56e8b2b6f7f06a1410413c9a41429d296d2d050d7531c2c21d22c0f3205f45fbd54bed35311dd64bc482613df91380b6",
          "sha256": "39a7aa3e7cd64f5dc72883746cf9b11862443aa5a22a5ba41f4743bc4f720d51",
          "sha1": "754994f9c2e71c58c1b861a8bac18e93ddf7f641",
          "md5": "98ca89c6f9845904ca6aac44e4faee27"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "size": 97042545,
          "sha512": "0dc46e7f906566b0364c1ec3229ea220e81c9cb15010959d1cbd2093825833e00b106ea5897de4baf7528346bf7425669355e719e1e9960052d018213ba1a90d",
          "sha256": "3ba0b1ef39e8520ea3a20756ee11fbe32f54bf88ea7b203e5935f6d5cfe1bfca",
          "sha1": "144378a468a68c4801e5f5de38dc0309ed483a04",
          "md5": "1e93acd88e7b058cf30aab1e914022ae"
        }
      ]
    }
  ]
}
